server:
  port: 8000
spring:
  web:
    resources:
      static-locations: /static/
  thymeleaf:
    prefix: /static/
  data:
    mongodb:
#      username: super_pay
#      password: 6d2880f9f562108b
#      uri:  mongodb://127.0.0.1:27017/super_pay
      port: 27017
      host: 127.0.0.1
      database: super_pay