server:
  port: 8000
spring:
  web:
    resources:
      static-locations: /static/
  thymeleaf:
#    prefix: /static/
    prefix: classpath:/
    cache: false
  data:
    mongodb:
#      username: super_pay
#      password: 6d2880f9f562108b
      uri:  mongodb://super-os:27017/super_pay
#      port: 27017
#      host: 172.21.72.18
#      database: super_pay

